auth_token: NzY2NTAxNDM2OTYzOTQ2NDk3.X4kSFw.0oZrFEiFi4k-canLYa5v3iEGOtc
gonks:
  - name: KrizhanLewis
    discriminator: '3469'
  - name: Crckr_Hckr
    discriminator: '6608'
chooms:
  - name: Ubermensch
    discriminator: '7211'
  - name: Bloodhound93
    discriminator: '3522'
