auth_token: NzY2NTAxNDM2OTYzOTQ2NDk3.X4kSFw.0oZrFEiFi4k-canLYa5v3iEGOtc
gonks:
  - name: krizhanlewis
    discriminator: '3469'
chooms:
  - name: joshie17
    discriminator: '9241'
  - name: ubermensch
    discriminator: '7211'
birthdayBoy:
